<a href="https://colab.research.google.com/github/Mohan24047/LIVE-AI/blob/main/NLP_WordEmbeddings_CNN_Question_P1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
# Define the size of the word embedding vectors and save it in the variable 'N'
N = 3

# Define V. Remember this was the size of the vocabulary in the previous lecture notebooks
V = 5

In [ ]:
import numpy as np

# Set seed for reproducibility
np.random.seed(42)

# Random initialization of weight matrices
W1 = np.random.rand(3, 5) * 2 - 1  # Values between -1 and 1
W2 = np.random.rand(5, 3) * 2 - 1

# Random initialization of bias vectors
b1 = np.random.rand(3, 1) * 2 - 1
b2 = np.random.rand(5, 1) * 2 - 1

print("W1:\n", W1)
print("W2:\n", W2)
print("b1:\n", b1)
print("b2:\n", b2)


W1:
 [[-0.25091976  0.90142861  0.46398788  0.19731697 -0.68796272]
 [-0.68801096 -0.88383278  0.73235229  0.20223002  0.41614516]
 [-0.95883101  0.9398197   0.66488528 -0.57532178 -0.63635007]]
W2:
 [[-0.63319098 -0.39151551  0.04951286]
 [-0.13610996 -0.41754172  0.22370579]
 [-0.72101228 -0.4157107  -0.26727631]
 [-0.08786003  0.57035192 -0.60065244]
 [ 0.02846888  0.18482914 -0.90709917]]
b1:
 [[ 0.2150897 ]
 [-0.65895175]
 [-0.86989681]]
b2:
 [[ 0.89777107]
 [ 0.93126407]
 [ 0.6167947 ]
 [-0.39077246]
 [-0.80465577]]


In [ ]:
# Define first matrix of weights
W1 = np.array([[ 0.41687358,  0.08854191, -0.23495225,  0.28320538,  0.41800106],
               [ 0.32735501,  0.22795148, -0.23951958,  0.4117634 , -0.23924344],
               [ 0.26637602, -0.23846886, -0.37770863, -0.11399446,  0.34008124]])

# Define second matrix of weights
W2 = np.array([[-0.22182064, -0.43008631,  0.13310965],
               [ 0.08476603,  0.08123194,  0.1772054 ],
               [ 0.1871551 , -0.06107263, -0.1790735 ],
               [ 0.07055222, -0.02015138,  0.36107434],
               [ 0.33480474, -0.39423389, -0.43959196]])

# Define first vector of biases
b1 = np.array([[ 0.09688219],
               [ 0.29239497],
               [-0.27364426]])

# Define second vector of biases
b2 = np.array([[ 0.0352008 ],
               [-0.36393384],
               [-0.12775555],
               [-0.34802326],
               [-0.07017815]])

In [ ]:
print(f'V (vocabulary size): {V}')
print(f'N (embedding size / size of the hidden layer): {N}')
print(f'size of W1: {W1.shape} (NxV)')
print(f'size of b1: {b1.shape} (Nx1)')
print(f'size of W2: {W2.shape} (VxN)')
print(f'size of b2: {b2.shape} (Vx1)')

V (vocabulary size): 5
N (embedding size / size of the hidden layer): 3
size of W1: (3, 5) (NxV)
size of b1: (3, 1) (Nx1)
size of W2: (5, 3) (VxN)
size of b2: (5, 1) (Vx1)


In [ ]:
import numpy as np

# Define the tokenized version of the corpus
words = ['i', 'am', 'happy', 'because', 'i', 'am', 'learning']

# Define the 'get_dict' function
def get_dict(words):
    """
    Generates a dictionary that maps words to indices and vice versa.

    Args:
        words (list): A list of words.

    Returns:
        tuple: Two dictionaries:
            - word2Ind: A dictionary mapping words to indices.
            - Ind2word: A dictionary mapping indices to words.
    """
    word2Ind = {}
    Ind2word = {}

    for index, word in enumerate(sorted(set(words))):  # Ensure unique words and sorted for consistency
        word2Ind[word] = index
        Ind2word[index] = word

    return word2Ind, Ind2word

# Get 'word2Ind' and 'Ind2word' dictionaries for the tokenized corpus
word2Ind, Ind2word = get_dict(words)

# Define the 'get_windows' function
def get_windows(words, C):
    i = C
    while i < len(words) - C:
        center_word = words[i]
        context_words = words[(i - C):i] + words[(i+1):(i+C+1)]
        yield context_words, center_word
        i += 1

# Define the 'word_to_one_hot_vector' function
def word_to_one_hot_vector(word, word2Ind, V):
    one_hot_vector = np.zeros(V)
    one_hot_vector[word2Ind[word]] = 1
    return one_hot_vector

# Define the 'context_words_to_vector' function
def context_words_to_vector(context_words, word2Ind, V):
    context_words_vectors = [word_to_one_hot_vector(w, word2Ind, V) for w in context_words]
    context_words_vectors = np.mean(context_words_vectors, axis=0)
    return context_words_vectors

# Define the generator function 'get_training_example' as seen in a previous notebook
def get_training_example(words, C, word2Ind, V):
    for context_words, center_word in get_windows(words, C):
        yield context_words_to_vector(context_words, word2Ind, V), word_to_one_hot_vector(center_word, word2Ind, V)

In [ ]:

# Save generator object in the 'training_examples' variable with the desired arguments
training_examples = get_training_example(words, 2, word2Ind, V)


In [ ]:
# Get first values from generator
x_array, y_array = next(training_examples)


In [ ]:

# Print one hot vector of center word
y_array

array([0., 0., 1., 0., 0.])

In [ ]:
# Copy vector
x = x_array.copy()

# Reshape it
x.shape = (V, 1)

# Print it
print(f'x:\n{x}\n')

# Copy vector
y = y_array.copy()

# Reshape it
y.shape = (V, 1)

# Print it
print(f'y:\n{y}')

x:
[[0.25]
 [0.25]
 [0.  ]
 [0.5 ]
 [0.  ]]

y:
[[0.]
 [0.]
 [1.]
 [0.]
 [0.]]


In [ ]:
# Define the 'relu' function
def relu(z):
    #To get the ReLU of this vector, you want all the negative values to become zeros.
    #Create copy of vector and save it in the 'h' variable
    #Determine which values met the criteria (this is possible because of vectorization)
    # Slice the array or vector. This is the same as applying ReLU to it
    #
     return np.maximum(0, z)  # Ensure it returns the value

# Define weight matrices and biases
W1 = np.array([[0.41687358,  0.08854191, -0.23495225,  0.28320538,  0.41800106],
               [0.32735501,  0.22795148, -0.23951958,  0.4117634 , -0.23924344],
               [0.26637602, -0.23846886, -0.37770863, -0.11399446,  0.34008124]])

W2 = np.array([[-0.22182064, -0.43008631,  0.13310965],
               [ 0.08476603,  0.08123194,  0.1772054 ],
               [ 0.1871551 , -0.06107263, -0.1790735 ],
               [ 0.07055222, -0.02015138,  0.36107434],
               [ 0.33480474, -0.39423389, -0.43959196]])

b1 = np.array([[0.09688219],
               [0.29239497],
               [-0.27364426]])

b2 = np.array([[0.0352008 ],
               [-0.36393384],
               [-0.12775555],
               [-0.34802326],
               [-0.07017815]])

# Define the 'softmax' function
def softmax(z):
    #You'll need to calculate the exponentials of each element, both for the numerator and for the denominator.
    # Save exponentials of the values in a new vector
    # Save the sum of the exponentials
    exp_z = np.exp(z - np.max(z))  # Subtract max(z) for numerical stability
    return exp_z / np.sum(exp_z, axis=0, keepdims=True)
    pass


In [ ]:
# Define a new vector and save it in the 'z' variable
z = np.array([[-1.25459881], [ 4.50714306], [ 2.31993942], [ 0.98658484], [-3.4398136 ]])

# Apply ReLU to it
relu(z)

array([[0.        ],
       [4.50714306],
       [2.31993942],
       [0.98658484],
       [0.        ]])

In [ ]:


# Print softmax values for original vector
softmax([9, 8, 11, 10, 8.5])
print (np.sum(softmax([9, 8, 11, 10, 8.5])))

1.0


In [ ]:
# Compute z1 (values of first hidden layer before applying ReLU)
z1 = np.dot(W1, x) + b1  # W1 * X + b1


In [ ]:


# Print z1
z1

array([[ 0.36483875],
       [ 0.63710329],
       [-0.3236647 ]])

In [ ]:


# Compute h (z1 after applying ReLU function)
h = relu(z1)

# Print h
h

array([[0.36483875],
       [0.63710329],
       [0.        ]])

In [ ]:
# Compute z2 (values of the output layer before applying the softmax function)
z2 = np.dot(W2, h) + b2

# Print z2
z2

array([[-0.31973737],
       [-0.28125477],
       [-0.09838369],
       [-0.33512159],
       [-0.19919612]])

In [ ]:

# Compute y_hat (z2 after applying softmax function)
y_hat = softmax(z2)

# Print y_hat
y_hat

array([[0.18519074],
       [0.19245626],
       [0.23107446],
       [0.18236353],
       [0.20891502]])

In [ ]:
print(Ind2word[np.argmax(y_hat)])

happy


In [ ]:
# Print prediction
y_hat


array([[0.18519074],
       [0.19245626],
       [0.23107446],
       [0.18236353],
       [0.20891502]])

In [ ]:

# Print target value
y

array([[0.],
       [0.],
       [1.],
       [0.],
       [0.]])

In [ ]:
def cross_entropy_loss(y_predicted, y_actual):
    loss = np.sum(-np.log(y_predicted) * y_actual)  # Compute loss
    return loss

In [ ]:

# Print value of cross entropy loss for prediction and target value
cross_entropy_loss(y_hat, y)

np.float64(1.4650152923611108)

In [ ]:
grad_b2 = y_hat - y

grad_b2


array([[ 0.18519074],
       [ 0.19245626],
       [-0.76892554],
       [ 0.18236353],
       [ 0.20891502]])

In [ ]:
# Compute matrix with partial derivatives of loss function with respect to W2
grad_W2 = np.dot(grad_b2, h.T)
# Print matrix
grad_W2


array([[ 0.06756476,  0.11798563,  0.        ],
       [ 0.0702155 ,  0.12261452,  0.        ],
       [-0.28053384, -0.48988499,  0.        ],
       [ 0.06653328,  0.1161844 ,  0.        ],
       [ 0.07622029,  0.13310045,  0.        ]])

In [ ]:
# Compute vector with partial derivatives of loss function with respect to b1
grad_b1 = relu(np.dot(W2.T, y_hat - y))

# Print vector
grad_b1

array([[0.        ],
       [0.        ],
       [0.17045858]])

In [ ]:


# Compute matrix with partial derivatives of loss function with respect to W1
grad_W1 = np.dot(relu(np.dot(W2.T, y_hat - y)), x.T)

# Print matrix
grad_W1

array([[0.        , 0.        , 0.        , 0.        , 0.        ],
       [0.        , 0.        , 0.        , 0.        , 0.        ],
       [0.04261464, 0.04261464, 0.        , 0.08522929, 0.        ]])

In [ ]:
print(f'V (vocabulary size): {V}')
print(f'N (embedding size / size of the hidden layer): {N}')
print(f'size of grad_W1: {grad_W1.shape} (NxV)')
print(f'size of grad_b1: {grad_b1.shape} (Nx1)')
print(f'size of grad_W2: {grad_W2.shape} (VxN)')
print(f'size of grad_b2: {grad_b2.shape} (Vx1)')

V (vocabulary size): 5
N (embedding size / size of the hidden layer): 3
size of grad_W1: (3, 5) (NxV)
size of grad_b1: (3, 1) (Nx1)
size of grad_W2: (5, 3) (VxN)
size of grad_b2: (5, 1) (Vx1)



# Define alpha
alpha = 0.03

In [ ]:
W1_new = W1 - alpha * grad_W1

In [ ]:
print('old value of W1:')
print(W1)
print()
print('new value of W1:')
print(W1_new)

old value of W1:
[[ 0.41687358  0.08854191 -0.23495225  0.28320538  0.41800106]
 [ 0.32735501  0.22795148 -0.23951958  0.4117634  -0.23924344]
 [ 0.26637602 -0.23846886 -0.37770863 -0.11399446  0.34008124]]

new value of W1:
[[ 0.41687358  0.08854191 -0.23495225  0.28320538  0.41800106]
 [ 0.32735501  0.22795148 -0.23951958  0.4117634  -0.23924344]
 [ 0.26509758 -0.2397473  -0.37770863 -0.11655134  0.34008124]]


In [ ]:
# Compute updated W2
W2_new = W2 - alpha * grad_W2  # W2_new = W2 - α * ∂L/∂W2

# Compute updated b1
b1_new = b1 - alpha * grad_b1  # b1_new = b1 - α * ∂L/∂b1

# Compute updated b2
b2_new = b2 - alpha * grad_b2  # b2_new = b2 - α * ∂L/∂b2

print('W2_new')
print(W2_new)
print()
print('b1_new')
print(b1_new)
print()
print('b2_new')
print(b2_new)

W2_new
[[-0.22384758 -0.43362588  0.13310965]
 [ 0.08265956  0.0775535   0.1772054 ]
 [ 0.19557112 -0.04637608 -0.1790735 ]
 [ 0.06855622 -0.02363691  0.36107434]
 [ 0.33251813 -0.3982269  -0.43959196]]

b1_new
[[ 0.09688219]
 [ 0.29239497]
 [-0.27875802]]

b2_new
[[ 0.02964508]
 [-0.36970753]
 [-0.10468778]
 [-0.35349417]
 [-0.0764456 ]]


In [2]:
# Import Python libraries and helper functions (in utils2)
import nltk
from nltk.tokenize import word_tokenize
import numpy as np
from collections import Counter
from utils2 import sigmoid, get_batches, compute_pca, get_dict

In [4]:
# Download sentence tokenizer
import nltk

nltk.download('punkt_tab')
nltk.data.path.append('.')
# Load, tokenize and process the data
import re                                                           #  Load the Regex-modul
with open('shakespeare.txt') as f:
    data = f.read()                                                 #  Read in the data
data = re.sub(r'[,!?;-]', '.',data)                                 #  Punktuations are replaced by .
data = nltk.word_tokenize(data)                                     #  Tokenize string to words
data = [ ch.lower() for ch in data if ch.isalpha() or ch == '.']    #  Lower case and drop non-alphabetical tokens
print("Number of tokens:", len(data),'\n', data[:15])               #  print data sample


[nltk_data] Downloading package punkt_tab to /root/nltk_data...
[nltk_data]   Unzipping tokenizers/punkt_tab.zip.


Number of tokens: 19808 
 ['the', 'sonnets', 'by', 'william', 'shakespeare', 'from', 'fairest', 'creatures', 'we', 'desire', 'increase', '.', 'that', 'thereby', 'beauty']


In [5]:
# Compute the frequency distribution of the words in the dataset (vocabulary)
fdist = nltk.FreqDist(word for word in data)
print("Size of vocabulary: ",len(fdist) )
print("Most frequent tokens: ",fdist.most_common(20) ) # print the 20 most frequent words and their freq.


Size of vocabulary:  3002
Most frequent tokens:  [('.', 2413), ('and', 490), ('the', 432), ('to', 408), ('my', 393), ('of', 370), ('i', 349), ('that', 323), ('in', 323), ('thy', 287), ('thou', 234), ('love', 188), ('with', 181), ('is', 180), ('not', 176), ('for', 171), ('me', 164), ('but', 163), ('a', 163), ('thee', 162)]


In [6]:
# get_dict creates two dictionaries, converting words to indices and viceversa.
word2Ind, Ind2word = get_dict(data)
V = len(word2Ind)
print("Size of vocabulary: ", V)

Size of vocabulary:  3002


In [8]:
# example of word to index mapping
print("Index of the word 'king' :  ",word2Ind['king'] )
print("Index of the word 'queen' :  ",word2Ind['queen'] ) # Changed 'Queen' to 'queen'
print("Word which has index 2743:  ",Ind2word[2743] )

Index of the word 'king' :   1405
Index of the word 'queen' :   1984
Word which has index 2743:   uphold
